name: Generate Snake
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout your repo
      - uses: actions/checkout@v3

      # Create 'dist' folder
      - name: Create dist folder
        run: mkdir -p dist

      # Generate the snake SVGs
      - uses: Platane/snk/svg-only@v3
        with:
          github_user_name: Darkwebnew
          outputs: dist/github-snake.svg,dist/github-snake-dark.svg?palette=github-dark

      # Push to output branch (force-create if it doesn't exist)
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
          commit_message: "Generate GitHub Snake"
          keep_files: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
